sudo: required
dist: trusty

language: java
jdk:
- openjdk8

env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: ./gradlew setupCIWorkspace
script: ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false

after_success:
  - ./gradlew travisPublish

deploy:
  file_glob: true
  provider: releases
  api-key: ${KEY}
  file: "./build/libs/FoxCore*.jar"
  skip_cleanup: true
  on:
    tags: true
